resolver: nightly-2025-05-28
compiler: ghc-9.12.2

packages:
- .

extra-deps:
  - git: https://github.com/t-sasaki915/ConsoleAsk
    commit: b518fb35c7f9f6858cd090ecda381ece9dc3566a
  
  - git: https://github.com/t-sasaki915/heredoc
    commit: 4cbb2fbe7e2e8821b38fde94f7cdcde0620c0f17
