resolver: nightly-2025-05-28
compiler: ghc-9.12.2

packages:
- .

extra-deps:
  - git: https://github.com/t-sasaki915/heredoc
    commit: 9cd60269959a247b2aff42a0af33fcdda2570c46
  
  - ConsoleAsk-0.1.0.1
